### ISSUE TITLE
RLP encoding for single byte between 0x80 and 0xff is incorrect

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#100]
RLP Encoding of a single byte between 0x80 and 0xff is incorrect due to the missing boundary check for a single byte RLP encoding. Thus it is right now impossible to compute correctly bytes for the transaction with nonce 0x80 to 0xff.

**Comment by 0crat** [comment]
The job [#100](https://github.com/blockstoreapp/web3swift/issues/100) assigned to @biboran[/z](https://www.0crat.com/u/biboran), here is [why](https://www.0crat.com/footprint/G930TRU1E/1081643294); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)We should be aware that biboran is on vacation; this ticket may be delayed

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#100` already assigned to @biboran, can't assign to @biboran

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by biboran** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/BlockStoreApp/Web3Swift/issues/100#issuecomment-382461289))

@biboran The impediment for [#100](https://github.com/blockstoreapp/web3swift/issues/100) was registered successfully by @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
The job [#100](https://github.com/blockstoreapp/web3swift/issues/100) is now out of scope
