### ISSUE TITLE
Missing convenience ctor for EthPrivateKey

### ISSUE THREAD

**Issue by rockfridrich** [BlockStoreApp/Web3Swift#105]
Let's add `hex` and `StringScalar` ctors to `EthPrivateKey`

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#105` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
