### ISSUE TITLE
Replace VerifiedProcedure with VerifiedNetwork

### ISSUE THREAD

**Issue by rockfridrich** [BlockStoreApp/Web3Swift#106]
It looks extraneous to wrap each `RemoteProcedure` in `VerifiedProcedure`. Let's check `JSON` structure in a decorator for `SimpleNetwork` and throw an error there.

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#106` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
