### ISSUE TITLE
Missing some ACL rules and specification

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#113]
Currently such code does not produce a warning/error.

```swift
public class A {

  init() { } //<- missing explicit acl warning

}
```

Thus user of the library cannot construct such object without `@testing` import modificator because objects ctor defaults to `internal`.

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#113` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
