### ISSUE TITLE
Missing and incorrect licensing in some files

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#114]
Licensing should be corrected to the version specified in [CONTIBUTING.md](https://github.com/BlockStoreApp/Web3Swift/blob/develop/CONTRIBUTING.md).

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#114` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
