### ISSUE TITLE
Contract call finishes with error

### ISSUE THREAD

**Issue by kondranton** [BlockStoreApp/Web3Swift#123]
Error description:
```
Code: (-32000) Custom error, Message: gas required exceeds allowance or always failing transaction, Data: null
```
Executed code example:

 ```
    let contractBytes = EthContractCallBytes(
      network: VerifiedNetwork(origin: InfuraNetwork(chain: "mainnet", apiKey: "metamask")),
      senderKey: senderKey,
      contractAddress: contractAddress,
      weiAmount: weiAmount,
      functionCall: EncodedABIFunction(
        signature: SimpleString(
          string: "fillOrder(address[5],uint256[6],uint256,bool,uint8,bytes32,bytes32)"
        ),
        parameters: [
         // some parameters
        ]
      )
    )
    return try SendRawTransactionProcedure(
      network: VerifiedNetwork(origin: InfuraNetwork(chain: "mainnet", apiKey: "metamask")),
      transactionBytes: contractBytes
    ).call()
```

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) please, pay attention to this issue

**Comment by biboran** [comment]
@kondranton can you give an example of parameters you are supplying? 

Is there any chance you are using `ABITuple` for `address[5]` and `uint256[6]`? There is a technical constraint right now that makes it impossible to perfectly replicate some fixed length collection semantics. If that's the case can you please try applying parameters as if they were flatmapped (like `address[5]` would be `address,address,address,address,address`) but don't change the signature.

**Comment by kondranton** [comment]
@biboran I tried to call without `ABITuple` usage, but the same error occurs.

ABI types that I use in my call are:
- `ABIFixedBytes`
- `ABIBoolean`
- `ABIUnsignedNumber`
- `ABIAddress`

Maybe that will help.

**Comment by biboran** [comment]
@kondranton I found a bug in `QuantityParameter` that was causing this error. It's encoding value of `0` as a string `"0x"` when it should be `"0x0"`.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
