### ISSUE TITLE
LeftZeroesPaddedBytes wrong length

### ISSUE THREAD

**Issue by kondranton** [BlockStoreApp/Web3Swift#124]
The result of the following call is `0` even though should be `32`.

```
LeftZeroesPaddedBytes(
        origin: SimpleBytes(
          bytes: []
        ),
        length: 32
).value().count
```

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) please, pay attention to this issue

**Comment by biboran** [comment]
@kondranton this is the intended behavior.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
