### ISSUE TITLE
Missing eth_signedTypedData 

### ISSUE THREAD

**Issue by rockfridrich** [BlockStoreApp/Web3Swift#38]
https://github.com/ethereum/EIPs/pull/712
https://github.com/changtimwu/changtimwu.github.com/issues/86

**Comment by 0crat** [comment]
The job [#38](https://github.com/blockstoreapp/web3swift/issues/38) assigned to @biboran[/z](https://www.0crat.com/u/biboran), here is [why](https://www.0crat.com/footprint/G930TRU1E/931626345); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by biboran** [comment]
This issue should be redefined

**Comment by biboran** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/BlockStoreApp/Web3Swift/issues/38#issuecomment-378571680))

@biboran This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#38](https://github.com/blockstoreapp/web3swift/issues/38) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @biboran[/z](https://www.0crat.com/u/biboran) for [19hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @rockfridrich[/z](https://www.0crat.com/u/rockfridrich): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/G930TRU1E?q=%7Bjob%3A%27gh%3Ablockstoreapp%2Fweb3swift%2338%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by biboran** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/BlockStoreApp/Web3Swift/issues/38#issuecomment-378572702))

@biboran GitHub issue is still open, won't close

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
The job [#38](https://github.com/blockstoreapp/web3swift/issues/38) is now out of scope

**Comment by 0crat** [comment]
I'm not managing `zeriontech/web3swift` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
