### ISSUE TITLE
SECP256k1SignatureTests do not test business scenarios

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#44]
We need to implement proper tests as in [EIP 155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)

We should also take data for testing from MyEtherWallet. Beware that parameters that are displayed on MyEtherWallet might not be correct.

**Comment by biboran** [comment]
I believe this is no longer relevant

**Comment by 0crat** [comment]
The job [#44](https://github.com/blockstoreapp/web3swift/issues/44) is now out of scope
