### ISSUE TITLE
Missing RLP tests for transaction signing

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#49]
These are actually integration tests between `SECP256k1Signature` and `SimpleRLP` but I think we can put them into `RLPTests` for now.

**Comment by biboran** [comment]
Not relevant any longer

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0688340c-9590-457f-a86c-7bf91a4c9a6a, thread: AsyncFlush-7
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/biboran.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1271451662, Type: 'Close job', Author: biboran
