### ISSUE TITLE
Missing JSON-RPC errors handling 

### ISSUE THREAD

**Issue by rockfridrich** [BlockStoreApp/Web3Swift#58]
If JSON-RPC returns an error in JSON than network layer should throw an error with description

**Comment by 0crat** [comment]
The job [#58](https://github.com/blockstoreapp/web3swift/issues/58) assigned to @biboran[/z](https://www.0crat.com/u/biboran), here is [why](https://www.0crat.com/footprint/G930TRU1E/931628406); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)We should be aware that biboran is on vacation; this ticket may be delayed

**Comment by biboran** [comment]
I don't like the approach of checking the response every time to see if it has `response` or `error` field.

`SwiftyJSON` doesn't retain the bottom of the JSON tree, therefore it will not be possible to check for error nonredunduntly. We need to implement support for climbing JSON tree first.

**Comment by biboran** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/BlockStoreApp/Web3Swift/issues/58#issuecomment-380780286))

@biboran The impediment for [#58](https://github.com/blockstoreapp/web3swift/issues/58) was registered successfully by @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
The job [#58](https://github.com/blockstoreapp/web3swift/issues/58) is now out of scope

**Comment by 0crat** [comment]
I'm not managing `zeriontech/web3swift` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
