### ISSUE TITLE
Missing abstraction for working with big numbers

### ISSUE THREAD

**Issue by rockfridrich** [BlockStoreApp/Web3Swift#60]
We will have to deal with big numbers (256-bit integers). 
For example, in issue #55 we will already have an overflow with this address [0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98](https://etherscan.io/address/0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98)
The quickest way will be using this [library](https://github.com/attaswift/BigInt)

**Comment by biboran** [comment]
I gave it a though and I think we should get rid of `NumberScalar`. Let's model all numbers as 2s complements `BytesScalar` and make a bunch of objects to validate and operate on those numbers. Let's also make a `StringScalar` to convert them to string representation decimal.

**Comment by rockfridrich** [comment]
@biboran the first arithmetic and comparison operations I got in mind is checking if the user has enough Ether of tokens to perform the procedure. In the case of ether, we are checking account balance, sending amount and transaction fee. In case the user does not have enough Ether we can throw an error in high domain objects. 

For the decimals, we often convert large `Int`s to decimal numbers based on some power. For example, ETH is 10^18 WEI or gas price is calculated in Gwei (10^9). Another example, the token balance is calculated and displayed as: 
`{balance}/10^{token decimals}`, however when we perform calls and transactions to contract we need to deal with integers.

We need to cover these use cases to simplify everyday operations. Here are some ideas about how to structure number classes. 
<img width="319" alt="screen shot 2018-05-19 at 17 47 05" src="https://user-images.githubusercontent.com/4190988/40269934-b4e695d8-5b8d-11e8-876d-b328d40ad8af.png">

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#60` is not assigned, can't get performer
