### ISSUE TITLE
FakeEthereumNetwork is not actually a fake

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#71]
`FakeEthereumNetwork` is actually a mainnet. We should either make it actually fake (it shouldn't communicate to any ethereum network) or rename it to `KovanEthereumNetwork` and make it point to the kovan testnet.

**Comment by 0crat** [comment]
The job [#71](https://github.com/blockstoreapp/web3swift/issues/71) assigned to @biboran[/z](https://www.0crat.com/u/biboran), here is [why](https://www.0crat.com/footprint/G930TRU1E/931638678); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)We should be aware that biboran is on vacation; this ticket may be delayed

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#71` already assigned to @biboran, can't assign to @biboran

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
The job [#71](https://github.com/blockstoreapp/web3swift/issues/71) is now out of scope
