### ISSUE TITLE
Missing RLP logic specific to ethereum

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#75]
All quantities of number "0" that are to be RLP encoded must be converted to an empty byte arrays to be encoded by standard RLP algorithm. 

I am thinking about something like `EthRLP: RLP` that can accept `Hex`, verify it for equality to a `ZeroHex`, modify as needed and be a proxy for `SimpleRLP`.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
