### ISSUE TITLE
Missing local network for tests 

### ISSUE THREAD

**Issue by rockfridrich** [BlockStoreApp/Web3Swift#84]
It is better to run behavior tests on the local network. We can use [Ganache](https://github.com/trufflesuite/ganache) and [Ganache CLI](https://github.com/trufflesuite/ganache-cli).

For this case, we need to run several bash scripts before test execution. Dependencies can be fetched via `yarn`.

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by biboran** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/BlockStoreApp/Web3Swift/issues/84#issuecomment-374916184))

@biboran The impediment for [#84](https://github.com/blockstoreapp/web3swift/issues/84) was registered successfully by @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
I'm not managing `zeriontech/web3swift` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
