### ISSUE TITLE
Missing encoded ABI parameters and functions 

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#93]
We need to implement encoding for contract functions and their parameters.

**Comment by 0crat** [comment]
The job [#93](https://github.com/blockstoreapp/web3swift/issues/93) assigned to @biboran[/z](https://www.0crat.com/u/biboran), here is [why](https://www.0crat.com/footprint/G930TRU1E/811643277); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#93` already assigned to @biboran, can't assign to @biboran

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by biboran** [comment]
Here are some notes as of 9797990:

1. Design of fixed static arrays seems to make them equivalent to abi tuples such as the argument of a function as a whole
2. All tuples directly inside tuples have to be logically flatmapped to be encoded correctly. Tuples inside dynamic collection inside tuples should not be flatmapped.

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @biboran[/z](https://www.0crat.com/u/biboran) resigned from [#93](https://github.com/blockstoreapp/web3swift/issues/93), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
The job [#93](https://github.com/blockstoreapp/web3swift/issues/93) is now out of scope
