### ISSUE TITLE
Missing wiki

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#96]
~~We should create some code samples of how one can deploy a contract as soon as #93 will be resolved.~~

We should instead write a proper wiki and add jazzy support.

**Comment by biboran** [comment]
@rockfridrich can we host a simple server at http://web3swift.io/wiki that will pull the repository on a github hook at generate it via `jazzy`?

**Comment by biboran** [comment]
@rockfridrich do you have time to do that right now in case we can? If you are busy I can write some backend for that task myself.

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#96` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
