### ISSUE TITLE
Missing contract call response interpretation

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#97]
We need to somehow interpret response from the contract function calls.

**Comment by biboran** [comment]
@rockfridrich is it possible to return any encodable Solidity type as of ethereum/solidity/issues/3270?

**Comment by rockfridrich** [comment]
`public` and `constant` function can return only primitives and tuples of primitives.

**Comment by biboran** [comment]
@rockfridrich I believe as of **0.4.22** variadic array can also be returned. See ethereum/solidity/pull/3308

But are they limited to a single dimension?

**Comment by biboran** [comment]
@rockfridrich how complex is the response usually? Is it common to return large tuples with many different types? Or is it usually a single value?

**Comment by rockfridrich** [comment]
@biboran it is usually a single value, however, tuples also exists.

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#97` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
