### ISSUE TITLE
EthTransactionBytes misses ABI call to the contract dependency 

### ISSUE THREAD

**Issue by biboran** [BlockStoreApp/Web3Swift#98]
Right now there is no way to sign a transaction that is supposed to call a contract. This is going to be an impediment for #96.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by biboran** [comment]
@rockfridrich is it possible to send ether directly to the contract (not to the `payable` function)?

**Comment by rockfridrich** [comment]
@biboran contract could implement default handler for receiving payments it coult rejects the transaction

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @biboran[/z](https://www.0crat.com/u/biboran) resigned from [#98](https://github.com/blockstoreapp/web3swift/issues/98), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
The job [#98](https://github.com/blockstoreapp/web3swift/issues/98) assigned to @driver733[/z](https://www.0crat.com/u/driver733), here is [why](https://www.0crat.com/footprint/G930TRU1E/1271448537); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)We should be aware that driver733 is on vacation; this ticket may be delayed

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#98](https://github.com/blockstoreapp/web3swift/issues/98) is now out of scope
